### ISSUE TITLE
python type can crash with UnicodeDecodeError

### ISSUE THREAD

**Issue by nembery** [PaloAltoNetworks/panhandler#50]
[2019-05-30 14:53:53,377: ERROR/ForkPoolWorker-2] Task pan_cnc.tasks.python3_execute_script[c791ac33-735f-4eda-bc3c-10a055030931] raised unexpected: UnicodeDecodeError('utf-8', b'./.venv/bin/python3: line 1: \xcf\xfa\xed\xfe\x07\x01\x03\x80\x02\x12\x80\x05\x85: not found\n', 29, 30, 'invalid continuation byte')
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 648, in __protected_call__
    return self.run(*args, **kwargs)
  File "/app/cnc/pan_cnc/tasks.py", line 222, in python3_execute_script
    return exec_local_task(cmd_seq, working_dir, env)
  File "/app/cnc/pan_cnc/tasks.py", line 76, in exec_local_task
    r = loop.run_until_complete(cmd_runner(cmd_seq, cwd, process_env, o))
  File "/usr/local/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "/app/cnc/pan_cnc/tasks.py", line 60, in cmd_runner
    o.add_output(line.decode())
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xcf in position 29: invalid continuation byte

No output is returned to the user

**Comment by nembery** [comment]
deleting .vevn and .python3_init_done can letting panhandler re-init the virtualenv solved the issue, but should handle that exception and allow a way out for the user

**Comment by nembery** [comment]
cannot reproduce now ...
